objects/TriggerOnnOff__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Permite determinar si se ejecutan ciertos desencadenadores de APEX o no.</description>
    <fields>
        <fullName>Opportunity_Trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Campo para activar e inactivar el trigger de oportunidades.</description>
        <inlineHelpText>Dejar en falso para que no se ejecute el desencadenador del objeto Opportunity</inlineHelpText>
        <label>Opportunity_Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger On/Off</label>
</CustomObject>

classes/Opportunity_Handler_cls.cls
/*#################################### Grupo SETGo #################################
Autor: Ing. Pedro Alan Sierra
Descripción: Handler del trigger Opportunity_Trigger_tgr
------------------------------------- Log de cambios -------------------------------
Fecha		Versión		Autor							Descripción
----------	-------		----------------------------	-------------------------			
27/01/2018	1.0			Ing. Pedro Alan Sierra			Creación
###################################################################################*/
public with sharing class Opportunity_Handler_cls extends TriggerHandler{
	
	public Opportunity_Handler_cls(){}

    /*protected override void beforeInsert() {
    	if(TriggerOnnOff__c.getInstance().Opportunity_Trigger__c){

        }
    }*/

    /*protected override void beforeUpdate(){
        if(TriggerOnnOff__c.getInstance().Opportunity_Trigger__c){

        }
    }*/

    /*protected override void beforeDelete(){
    	if(TriggerOnnOff__c.getInstance().Opportunity_Trigger__c){

        }
    }*/

    protected override void afterInsert(){
    	if(TriggerOnnOff__c.getInstance().Opportunity_Trigger__c){

        }
    }

    protected override void afterUpdate(){
        if(TriggerOnnOff__c.getInstance().Opportunity_Trigger__c){

        }
    }

    protected override void afterDelete(){
    	if(TriggerOnnOff__c.getInstance().Opportunity_Trigger__c){

        }
    }

    /*protected override void afterUndelete(){
    	if(TriggerOnnOff__c.getInstance().Opportunity_Trigger__c){

        }
    }*/

}